[package]
name = "sync-oneshot"
version = "0.2.0"
edition = "2024"
readme = "README.md"
repository = "https://github.com/locksmith-rs/sync-oneshot.git"
license = "MIT"
description = """
A minimal oneshot channel for synchronous Rust.
"""
documentation = "https://docs.rs/sync-oneshot"
keywords = ["channel", "oneshot", "message"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }

[dependencies]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
oneshot = { version = "0.2", features = ["std"] }
tokio = { version = "1", features = ["sync"] }

[target.'cfg(loom)'.dependencies]
loom = "0.7"

[[bench]]
name = "basic"
harness = false

[[bench]]
name = "thread"
harness = false
